const labState={data:null,tab:'constellation'};
const labEscape=value=>String(value==null?'':value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]);
const labIcons={flask:'<svg class="icon" viewBox="0 0 24 24"><path d="M9 3h6M10 3v6l-5.5 9.5A1.7 1.7 0 0 0 6 21h12a1.7 1.7 0 0 0 1.5-2.5L14 9V3M7.5 15h9"/></svg>',spark:'<svg class="icon" viewBox="0 0 24 24"><path d="m12 3 1.3 4.7L18 9l-4.7 1.3L12 15l-1.3-4.7L6 9l4.7-1.3z"/></svg>',clock:'<svg class="icon" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',radar:'<svg class="icon" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m12 12 6-6"/></svg>'};
const tabNames=[['constellation','Cultural constellation'],['capsule','Time capsule'],['serendipity','Serendipity engine'],['oracle','Viewing oracle']];

function labShell(){return '<button class="back-link" data-lab-back>← Command deck</button><div class="lab-hero"><div><span class="eyebrow">FUTURE LAB · EXPERIMENTAL</span><h1>Ideas from the<br><em>edge of your library.</em></h1><p>Local experiments built from the cultural shape and memory of your Plex universe.</p></div><div class="lab-reactor"><span>'+labIcons.flask+'</span><i></i><b>LIVE<br>EXPERIMENTS</b></div></div><div class="lab-status"><span><i></i>Read-only laboratory</span><b id="lab-catalog">Calibrating with Plex…</b><button id="refresh-lab">Recalculate</button></div><nav class="lab-tabs">'+tabNames.map((tab,index)=>'<button data-lab-tab="'+tab[0]+'" class="'+(index===0?'active':'')+'"><i>0'+(index+1)+'</i>'+tab[1]+'</button>').join('')+'</nav><div class="lab-stage" id="lab-stage"><div class="lab-loading"><span></span><h3>Mapping the edges</h3><p>Analysing relationships across your movie archive.</p></div></div>'}

function constellationView(data){return '<section class="lab-view constellation-view"><div class="view-copy"><span class="card-label">CULTURAL GRAPH</span><h2>Your library has a shape.</h2><p>Genres cluster around the filmmakers who appear most often in your collection. Hover over a signal to isolate its strongest relationships.</p><div class="graph-legend"><span><i></i>Genre</span><span><i></i>Director</span></div><div class="graph-top">'+data.graph.nodes.slice(0,6).map(node=>'<div><b>'+labEscape(node.label)+'</b><span>'+node.count+' titles</span></div>').join('')+'</div></div><div class="graph-wrap"><canvas id="culture-graph"></canvas><div id="graph-tooltip"></div></div></section>'}

function capsuleView(data){const peak=Math.max(1,...data.eras.map(item=>item.count));return '<section class="lab-view capsule-view"><div class="capsule-heading"><div><span class="card-label">LIBRARY TIME CAPSULE</span><h2>'+data.eras[0]?.decade+'s → '+data.eras[data.eras.length-1]?.decade+'s</h2><p>'+data.catalogSize.toLocaleString()+' films arranged across cinematic time.</p></div>'+labIcons.clock+'</div><div class="era-chart">'+data.eras.map(item=>'<div><i style="height:'+Math.max(4,Math.round(item.count/peak*100))+'%"><span>'+item.count+'</span></i><b>'+String(item.decade).slice(2)+'s</b></div>').join('')+'</div><div class="capsule-shelves"><div><span class="card-label">EARLIEST SIGNALS</span>'+data.oldest.map(item=>capsuleCard(item)).join('')+'</div><div><span class="card-label">NEWEST ARRIVALS</span>'+data.newest.map(item=>capsuleCard(item)).join('')+'</div></div></section>'}
function capsuleCard(item){return '<article><img src="'+labEscape(item.poster)+'" alt="" loading="lazy"><p><b>'+labEscape(item.title)+'</b><small>'+item.year+'</small></p></article>'}

function serendipityView(data){const pair=data.doubleFeature;return '<section class="lab-view serendipity-view"><div class="serendipity-copy"><span class="card-label">SERENDIPITY ENGINE · DAILY PAIRING</span><h2>Two films that should<br>never have met.</h2><p>Radar deliberately crosses distant genres to create an unexpected double feature from unwatched, highly rated films you already own.</p><div class="pair-equation"><span>CONTRAST</span><i>+</i><span>QUALITY</span><i>+</i><span>CURIOSITY</span></div></div><div class="double-feature">'+(pair.length===2?pair.map((item,index)=>'<article><div><img src="'+labEscape(item.poster)+'" alt=""><span>FEATURE '+(index+1)+'</span></div><h3>'+labEscape(item.title)+'</h3><p>'+item.year+' · '+item.durationMinutes+' min · ★ '+item.rating.toFixed(1)+'</p><small>'+item.genres.map(labEscape).join(' · ')+'</small></article>').join('<i class="pair-link">×</i>'):'<div class="lab-empty">More rated, unwatched films are needed to create a pairing.</div>')+'</div></section>'}

function oracleView(data){const oracle=data.oracle;const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];const hour=oracle.peakHour;const time=(hour%12||12)+(hour>=12?' PM':' AM');const watchedTotal=oracle.watchedMovies+oracle.unwatchedMovies;const watchedPercent=watchedTotal?Math.round(oracle.watchedMovies/watchedTotal*100):0;return '<section class="lab-view oracle-view"><div class="oracle-core"><span class="oracle-r1"></span><span class="oracle-r2"></span><i>'+oracle.confidence+'%</i><b>SIGNAL<br>CONFIDENCE</b></div><div class="oracle-copy"><span class="card-label">VIEWING ORACLE</span><h2>Your habits leave<br>a gentle signature.</h2><p>This is pattern recognition, not prediction. It describes the rhythms already present in your Plex history.</p><div class="oracle-grid"><article><span>PEAK HOUR</span><b>'+time+'</b><small>'+oracle.peakHourPlays+' sampled plays</small></article><article><span>PEAK DAY</span><b>'+days[oracle.peakDay]+'</b><small>'+oracle.peakDayPlays+' sampled plays</small></article><article><span>STRONGEST GENRE</span><b>'+labEscape(oracle.favouriteGenre)+'</b><small>'+oracle.favouriteGenreCount+' watched titles</small></article><article><span>EXPLORED</span><b>'+watchedPercent+'%</b><small>'+oracle.unwatchedMovies+' films still waiting</small></article></div></div></section>'}

function drawGraph(graph){const canvas=document.querySelector('#culture-graph');if(!canvas)return;const wrap=canvas.parentElement;const dpr=Math.min(devicePixelRatio||1,1.5);const width=wrap.clientWidth,height=Math.max(420,wrap.clientHeight);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+'px';canvas.style.height=height+'px';const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const cx=width/2,cy=height/2;const genres=graph.nodes.filter(n=>n.type==='genre'),directors=graph.nodes.filter(n=>n.type==='director');const positioned=[];genres.forEach((node,index)=>{const a=index/genres.length*Math.PI*2-Math.PI/2;positioned.push({...node,x:cx+Math.cos(a)*Math.min(width*.34,190),y:cy+Math.sin(a)*165,r:Math.max(7,Math.min(16,5+Math.sqrt(node.count)))});});directors.forEach((node,index)=>{const a=index/directors.length*Math.PI*2-Math.PI/2+.32;positioned.push({...node,x:cx+Math.cos(a)*Math.min(width*.19,100),y:cy+Math.sin(a)*92,r:Math.max(5,Math.min(11,4+Math.sqrt(node.count)*.5))});});const byId=new Map(positioned.map(n=>[n.id,n]));function paint(hover){ctx.clearRect(0,0,width,height);for(const edge of graph.edges){const a=byId.get(edge.source),b=byId.get(edge.target);if(!a||!b)continue;const active=!hover||a.id===hover.id||b.id===hover.id;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=active?'rgba(245,173,46,.3)':'rgba(110,122,140,.07)';ctx.lineWidth=Math.min(2,0.35+edge.weight/12);ctx.stroke();}for(const node of positioned){const active=!hover||node.id===hover.id||graph.edges.some(e=>(e.source===hover.id&&e.target===node.id)||(e.target===hover.id&&e.source===node.id));ctx.beginPath();ctx.arc(node.x,node.y,node.r,0,Math.PI*2);ctx.fillStyle=node.type==='genre'?'rgba(245,173,46,'+(active?.86:.16)+')':'rgba(80,214,209,'+(active?.82:.14)+')';ctx.shadowColor=node.type==='genre'?'#f5ad2e':'#50d6d1';ctx.shadowBlur=active?13:0;ctx.fill();ctx.shadowBlur=0;if(node.r>10){ctx.fillStyle=active?'#d8d9d5':'#646c78';ctx.font='7px DM Mono';ctx.textAlign='center';ctx.fillText(node.label.slice(0,18),node.x,node.y+node.r+12);}}}paint();canvas.onmousemove=event=>{const rect=canvas.getBoundingClientRect();const x=event.clientX-rect.left,y=event.clientY-rect.top;const hit=positioned.find(node=>Math.hypot(node.x-x,node.y-y)<node.r+7);paint(hit);const tip=document.querySelector('#graph-tooltip');if(hit){tip.textContent=hit.label+' · '+hit.count+' titles';tip.style.left=(hit.x+12)+'px';tip.style.top=(hit.y-10)+'px';tip.classList.add('visible');}else tip.classList.remove('visible');};canvas.onmouseleave=()=>{paint();document.querySelector('#graph-tooltip')?.classList.remove('visible');};}

function renderLab(){const stage=document.querySelector('#lab-stage');if(!stage||!labState.data)return;const views={constellation:constellationView,capsule:capsuleView,serendipity:serendipityView,oracle:oracleView};stage.innerHTML=views[labState.tab](labState.data);if(labState.tab==='constellation')requestAnimationFrame(()=>drawGraph(labState.data.graph));}
async function loadLab(force=false){const stage=document.querySelector('#lab-stage');if(!stage)return;stage.classList.add('loading');try{const response=await fetch('/api/lab'+(force?'?refresh=1':''));const data=await response.json();if(!response.ok)throw new Error(data.error);labState.data=data;document.querySelector('#lab-catalog').textContent=data.catalogSize.toLocaleString()+' films · '+data.historySample.toLocaleString()+' history signals';renderLab();}catch(error){stage.innerHTML='<div class="lab-empty"><b>Experiment interrupted</b><p>'+labEscape(error.message)+'</p></div>';}finally{stage.classList.remove('loading')}}
function setupLab(){const page=document.querySelector('#lab-page');if(!page)return;page.classList.add('future-lab');page.innerHTML=labShell();page.querySelector('[data-lab-back]').addEventListener('click',event=>{event.preventDefault();document.querySelector('[data-nav="dashboard"]').click()});page.querySelectorAll('[data-lab-tab]').forEach(button=>button.addEventListener('click',()=>{labState.tab=button.dataset.labTab;page.querySelectorAll('[data-lab-tab]').forEach(item=>item.classList.toggle('active',item===button));renderLab()}));page.querySelector('#refresh-lab').addEventListener('click',()=>loadLab(true));document.querySelector('[data-nav="lab"]').addEventListener('click',()=>{if(!labState.data)setTimeout(()=>loadLab(),70)});if(location.hash==='#lab')loadLab();window.addEventListener('resize',()=>{if(labState.tab==='constellation'&&labState.data)drawGraph(labState.data.graph)},{passive:true})}setupLab();
