const playlistState={data:null,selected:null};
const playlistEscape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const playlistDuration=minutes=>{const value=Number(minutes)||0;return value>=60?Math.floor(value/60)+'h '+value%60+'m':value+' min'};
const playlistIcon='<svg viewBox="0 0 24 24"><path d="M5 6h10M5 11h10M5 16h6"/><path d="m16 14 4 3-4 3z"/></svg>';

function studioShell(){return '<button class="back-link" data-playlist-back>← Command deck</button><header class="playlist-hero"><div><span class="eyebrow">PLAYLIST STUDIO · LIVE PLEX GENERATORS</span><h1>Build the queue.<br><em>Set the mood.</em></h1><p>Turn library signals into real Plex playlists. Every generator is explainable, previewed and created only after confirmation.</p></div><div class="playlist-orbit" aria-hidden="true"><i></i><i></i><span>'+playlistIcon+'</span><b>AUTO MIX</b></div></header><section class="playlist-stats"><article><span>CATALOG MAPPED</span><b id="playlist-catalog">—</b><small>Video items</small></article><article><span>GENERATORS READY</span><b id="playlist-generators">—</b><small>Live criteria</small></article><article><span>EXISTING PLAYLISTS</span><b id="playlist-existing-count">—</b><small>Currently in Plex</small></article><article><span>SAFETY</span><b>PREVIEW</b><small>Confirm before creation</small></article></section><section class="playlist-section"><header><div><span>AUTO-GENERATE</span><h2>Choose a signal</h2><p>Buttons are enabled only when your library has matching titles.</p></div><button id="playlist-refresh">Refresh criteria</button></header><div class="playlist-generators" id="playlist-generators-grid"><div class="playlist-loading"><i></i><span>Reading Plex criteria…</span></div></div></section><section class="playlist-section"><header><div><span>PLEX PLAYLISTS</span><h2>Already created</h2></div></header><div class="playlist-existing" id="playlist-existing"><div class="playlist-empty">Loading existing playlists…</div></div></section>'}

function samplePoster(item){return '<article title="'+playlistEscape(item.title)+'"><img src="'+playlistEscape(item.poster)+'" loading="lazy" alt=""><span>'+playlistEscape(item.title)+'</span></article>'}
function renderStudio(){const data=playlistState.data;if(!data)return;document.querySelector('#playlist-catalog').textContent=data.catalogSize.toLocaleString();document.querySelector('#playlist-generators').textContent=data.generators.filter(item=>item.available).length;document.querySelector('#playlist-existing-count').textContent=data.existing.length;const grid=document.querySelector('#playlist-generators-grid');grid.innerHTML=data.generators.map(generator=>'<article class="playlist-generator '+playlistEscape(generator.tone)+' '+(!generator.available?'unavailable':'')+'"><header><span>'+playlistEscape(generator.eyebrow)+'</span><b>'+generator.count.toLocaleString()+' matches</b></header><div class="playlist-generator-icon">'+playlistIcon+'</div><h3>'+playlistEscape(generator.name)+'</h3><p>'+playlistEscape(generator.description)+'</p><div class="playlist-samples">'+generator.sample.slice(0,4).map(samplePoster).join('')+'</div><footer><small>'+playlistDuration(generator.totalMinutes)+' total</small><button data-playlist-generate="'+playlistEscape(generator.id)+'" '+(!generator.available?'disabled':'')+'>'+(generator.available?'Auto generate':'No matches')+'</button></footer></article>').join('');grid.querySelectorAll('[data-playlist-generate]').forEach(button=>button.onclick=()=>openGenerator(data.generators.find(item=>item.id===button.dataset.playlistGenerate)));const existing=document.querySelector('#playlist-existing');existing.innerHTML=data.existing.length?data.existing.map(item=>'<article><span>'+playlistIcon+'</span><div><b>'+playlistEscape(item.title)+'</b><small>'+item.itemCount+' items'+(item.durationMinutes?' · '+playlistDuration(item.durationMinutes):'')+'</small></div></article>').join(''):'<div class="playlist-empty">No video playlists returned by Plex yet. Create your first one above.</div>'}

function previewItem(item,index){return '<article><span>'+String(index+1).padStart(2,'0')+'</span><img src="'+playlistEscape(item.poster)+'" loading="lazy" alt=""><div><b>'+playlistEscape(item.title)+'</b><small>'+playlistEscape(item.detail)+'</small></div><a href="'+playlistEscape(item.plexUrl)+'" target="_blank" rel="noopener noreferrer">Plex ↗</a></article>'}
function openGenerator(generator){playlistState.selected=generator;document.querySelector('.playlist-modal-wrap')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="playlist-modal-wrap"><div class="playlist-modal-backdrop"></div><section class="playlist-modal"><button class="playlist-modal-close">×</button><header><span>'+playlistEscape(generator.eyebrow)+' · '+generator.count+' MATCHES</span><h2>'+playlistEscape(generator.name)+'</h2><p>'+playlistEscape(generator.description)+'</p></header><div class="playlist-create-fields"><label>Playlist name<input id="playlist-name" maxlength="80" value="'+playlistEscape(generator.name)+'"></label><label>Maximum items<select id="playlist-limit">'+[10,20,30,50,100].map(value=>'<option value="'+value+'" '+(value===30?'selected':'')+'>'+Math.min(value,generator.count)+' items</option>').join('')+'</select></label></div><div class="playlist-preview-label"><span>PREVIEW · FIRST '+Math.min(12,generator.sample.length)+'</span><small>Final order follows the criterion ranking.</small></div><div class="playlist-preview">'+generator.sample.map(previewItem).join('')+'</div><footer><button class="playlist-cancel">Cancel</button><button class="playlist-create">Create in Plex</button></footer></section></div>');const wrap=document.querySelector('.playlist-modal-wrap'),close=()=>wrap.remove();wrap.querySelector('.playlist-modal-backdrop').onclick=close;wrap.querySelector('.playlist-modal-close').onclick=close;wrap.querySelector('.playlist-cancel').onclick=close;wrap.querySelector('.playlist-create').onclick=()=>createPlaylist(wrap,generator)}

async function createPlaylist(wrap,generator){const title=wrap.querySelector('#playlist-name').value.trim(),limit=Number(wrap.querySelector('#playlist-limit').value);if(!title)return wrap.querySelector('#playlist-name').focus();if(!window.confirm('Are you sure you want to create “'+title+'” in Plex with up to '+Math.min(limit,generator.count)+' items?'))return;const button=wrap.querySelector('.playlist-create');button.disabled=true;button.textContent='Creating…';try{const response=await fetch('/api/playlists/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({generatorId:generator.id,title,limit,confirmed:true})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Playlist creation failed');wrap.remove();await loadStudio(true);window.alert('Created “'+data.playlist.title+'” with '+data.playlist.itemCount+' items in Plex.')}catch(error){button.disabled=false;button.textContent='Create in Plex';window.alert(error.message)}}
async function loadStudio(force=false){const grid=document.querySelector('#playlist-generators-grid');if(!grid)return;grid.innerHTML='<div class="playlist-loading"><i></i><span>Evaluating playlist criteria…</span></div>';try{const response=await fetch('/api/playlists/studio'+(force?'?refresh=1':'')),data=await response.json();if(!response.ok)throw new Error(data.error||'Playlist Studio unavailable');playlistState.data=data;renderStudio()}catch(error){grid.innerHTML='<div class="playlist-empty error"><b>Playlist Studio is offline</b><span>'+playlistEscape(error.message)+'</span></div>'}}
function setupPlaylistStudio(){const page=document.querySelector('#playlists-page');if(!page)return;page.classList.add('playlist-studio');page.innerHTML=studioShell();page.querySelector('[data-playlist-back]').onclick=()=>document.querySelector('[data-nav="dashboard"]').click();page.querySelector('#playlist-refresh').onclick=()=>loadStudio(true);document.querySelector('[data-nav="playlists"]')?.addEventListener('click',()=>{if(!playlistState.data)setTimeout(()=>loadStudio(),80)});if(location.hash==='#playlists')loadStudio()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupPlaylistStudio);else setupPlaylistStudio();
