const cEscape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const cSpark='<svg viewBox="0 0 24 24"><path d="m12 3 1.3 4.7L18 9l-4.7 1.3L12 15l-1.3-4.7L6 9l4.7-1.3zM19 16l.6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6z"/></svg>';
const cSearch='<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>';
let searchTimer,searchResults=[],searchIndex=-1;

async function cRequest(path,options:any={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Companion could not complete that request.');return data}
function cAgo(value){const seconds=Math.max(0,Math.round((Date.now()-Date.parse(value))/1000));if(seconds<60)return'now';if(seconds<3600)return Math.floor(seconds/60)+'m';if(seconds<86400)return Math.floor(seconds/3600)+'h';return Math.floor(seconds/86400)+'d'}

function searchShell(){const host=document.querySelector('.search');if(!host||document.querySelector('#universe-search'))return;host.insertAdjacentHTML('beforeend','<section id="universe-search" class="universe-search"><div class="search-idle">'+cSearch+'<span>Search every connected Plex library</span><small>TYPE AT LEAST 2 CHARACTERS</small></div></section>')}
function renderSearch(data){const panel=document.querySelector('#universe-search');searchResults=data.results||[];searchIndex=-1;if(!searchResults.length){panel.innerHTML='<div class="search-idle empty">'+cSearch+'<span>No signal found for “'+cEscape(data.query)+'”</span><small>TRY ANOTHER TITLE, SERIES OR ARTIST</small></div>';return}const groups=new Map();for(const item of searchResults){const key=item.type||'media';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item)}panel.innerHTML='<div class="search-top"><span>PLEX UNIVERSE</span><b>'+searchResults.length+' MATCHES</b></div>'+[...groups].map(([type,items])=>'<div class="search-group"><label>'+cEscape(type.toUpperCase())+'</label>'+items.map((item,index)=>{const actual=searchResults.indexOf(item);return '<button class="search-result" data-index="'+actual+'"><span class="search-poster">'+(item.poster?'<img loading="lazy" src="'+cEscape(item.poster)+'" alt="">':cSpark)+'</span><span><b>'+cEscape(item.title)+'</b><small>'+cEscape([item.detail,item.year,item.library].filter(Boolean).join(' · '))+'</small></span><em>↗</em></button>'}).join('')+'</div>').join('');bindSearchResults()}
function bindSearchResults(){document.querySelectorAll('.search-result').forEach(button=>button.onclick=()=>openMedia(searchResults[Number(button.dataset.index)]))}
async function runSearch(query){const panel=document.querySelector('#universe-search');panel.classList.add('open');panel.innerHTML='<div class="search-scanning"><i></i><span>Scanning your Plex universe…</span></div>';try{renderSearch(await cRequest('/api/search?q='+encodeURIComponent(query)))}catch(error){panel.innerHTML='<div class="search-idle empty"><b>!</b><span>'+cEscape(error.message)+'</span></div>'}}
function selectSearch(direction){const buttons=[...document.querySelectorAll('.search-result')];if(!buttons.length)return;searchIndex=(searchIndex+direction+buttons.length)%buttons.length;buttons.forEach((item,index)=>item.classList.toggle('selected',index===searchIndex));buttons[searchIndex].scrollIntoView({block:'nearest'})}
function openMedia(item){document.querySelector('#universe-search')?.classList.remove('open');document.body.insertAdjacentHTML('beforeend','<div class="companion-overlay media-overlay"><div class="companion-backdrop"></div><section class="media-peek"><button class="companion-close">×</button><div class="media-peek-art">'+(item.poster?'<img src="'+cEscape(item.poster)+'" alt="">':cSpark)+'</div><div><span class="eyebrow">'+cEscape((item.type||'MEDIA').toUpperCase())+' · PLEX LIBRARY</span><h2>'+cEscape(item.title)+'</h2><p class="media-meta">'+cEscape([item.detail,item.year,item.durationMinutes?item.durationMinutes+' min':null,item.rating?'★ '+Number(item.rating).toFixed(1):null].filter(Boolean).join(' · '))+'</p><p>'+cEscape(item.summary||'No synopsis is available in Plex.')+'</p><small>'+cEscape(item.library||'Your library')+'</small></div></section></div>');const overlay=document.querySelector('.media-overlay');overlay.querySelector('.companion-close').onclick=()=>overlay.remove();overlay.querySelector('.companion-backdrop').onclick=()=>overlay.remove()}

function assistantMarkup(){return '<div class="companion-overlay assistant-overlay"><div class="companion-backdrop"></div><section class="real-assistant"><button class="companion-close">×</button><header><span class="companion-core">'+cSpark+'<i></i></span><div><span class="eyebrow">LOCAL COMPANION INTELLIGENCE</span><h2>Ask your universe.</h2><p>Answers are generated from your live Plex data—never sent outside your network.</p></div></header><form><input autofocus placeholder="What should I watch tonight?"><button>'+cSpark+' Ask</button></form><div class="assistant-prompts"><button>What should I watch tonight?</button><button>Is anything transcoding?</button><button>How much space can I reclaim?</button><button>What was recently added?</button><button>How are my automations?</button></div><div class="assistant-answer"><div class="answer-idle"><i></i><p>Try a prompt or ask about your library, streams, storage, arrivals or automations.</p></div></div></section></div>'}
function renderAnswer(data,host){host.innerHTML='<div class="answer-head"><span>'+cEscape(data.eyebrow)+'</span><h3>'+cEscape(data.headline)+'</h3><p>'+cEscape(data.answer)+'</p></div>'+(data.stats?.length?'<div class="answer-stats">'+data.stats.map(item=>'<span><b>'+cEscape(item[1])+'</b>'+cEscape(item[0])+'</span>').join('')+'</div>':'')+(data.cards?.length?'<div class="answer-cards">'+data.cards.map(item=>'<button><span>'+(item.poster?'<img src="'+cEscape(item.poster)+'" alt="">':cSpark)+'</span><b>'+cEscape(item.title)+'</b><small>'+cEscape([item.year,item.durationMinutes?item.durationMinutes+' min':null].filter(Boolean).join(' · '))+'</small></button>').join('')+'</div>':'')+(data.action?'<button class="answer-route">'+cEscape(data.action.label)+' <b>→</b></button>':'');host.querySelector('.answer-route')?.addEventListener('click',()=>{location.hash='#'+data.action.route;document.querySelector('.assistant-overlay')?.remove()});host.querySelectorAll('.answer-cards button').forEach((button,index)=>button.onclick=()=>openMedia(data.cards[index]))}
function openAssistant(){document.body.insertAdjacentHTML('beforeend',assistantMarkup());const overlay=document.querySelector('.assistant-overlay'),form=overlay.querySelector('form'),input=form.querySelector('input'),answer=overlay.querySelector('.assistant-answer');const close=()=>overlay.remove();overlay.querySelector('.companion-close').onclick=close;overlay.querySelector('.companion-backdrop').onclick=close;overlay.querySelectorAll('.assistant-prompts button').forEach(button=>button.onclick=()=>{input.value=button.textContent;form.requestSubmit()});form.onsubmit=async event=>{event.preventDefault();if(!input.value.trim())return;answer.innerHTML='<div class="answer-thinking"><span></span><b>Companion is reading Plex…</b><small>LOCAL ANALYSIS</small></div>';try{renderAnswer(await cRequest('/api/assistant',{method:'POST',body:JSON.stringify({question:input.value})}),answer)}catch(error){answer.innerHTML='<div class="answer-error"><b>!</b><p>'+cEscape(error.message)+'</p></div>'}}}

function notificationsMarkup(){return '<div class="companion-overlay notification-overlay"><div class="companion-backdrop"></div><aside class="notification-drawer"><header><div><span class="eyebrow">COMPANION SIGNAL</span><h2>Notifications</h2></div><button class="companion-close">×</button></header><div id="notification-list"><div class="notification-loading"><i></i>Reading live signals…</div></div><footer><i></i>Local events only · refreshed when opened</footer></aside></div>'}
function openNotifications(){document.body.insertAdjacentHTML('beforeend',notificationsMarkup());const overlay=document.querySelector('.notification-overlay'),close=()=>overlay.remove();overlay.querySelector('.companion-close').onclick=close;overlay.querySelector('.companion-backdrop').onclick=close;cRequest('/api/notifications').then(data=>{const list=overlay.querySelector('#notification-list');list.innerHTML=data.notifications.length?data.notifications.map(item=>'<button class="notification-item '+cEscape(item.tone)+'" data-route="'+cEscape(item.route)+'"><i></i><span><b>'+cEscape(item.title)+'</b><small>'+cEscape(item.body)+'</small></span><time>'+cAgo(item.at)+'</time></button>').join(''):'<div class="notification-empty">'+cSpark+'<h3>All signals are clear</h3><p>No failed automations, active transcodes or encodes awaiting review.</p></div>';list.querySelectorAll('[data-route]').forEach(button=>button.onclick=()=>{location.hash='#'+button.dataset.route;close()});document.querySelector('.icon-button[data-action="notifications"] .notice')?.remove();localStorage.setItem('companion-notifications-seen',new Date().toISOString())}).catch(error=>{overlay.querySelector('#notification-list').innerHTML='<div class="notification-empty"><b>!</b><p>'+cEscape(error.message)+'</p></div>'})}

function setupCompanionUI(){searchShell();const input=document.querySelector('#global-search');input.addEventListener('input',()=>{clearTimeout(searchTimer);const query=input.value.trim();const panel=document.querySelector('#universe-search');if(query.length<2){panel.classList.remove('open');return}searchTimer=setTimeout(()=>runSearch(query),220)});input.addEventListener('focus',()=>{if(input.value.trim().length>=2)document.querySelector('#universe-search').classList.add('open')});input.addEventListener('keydown',event=>{if(event.key==='ArrowDown'){event.preventDefault();event.stopImmediatePropagation();selectSearch(1)}else if(event.key==='ArrowUp'){event.preventDefault();event.stopImmediatePropagation();selectSearch(-1)}else if(event.key==='Enter'){event.preventDefault();event.stopImmediatePropagation();if(searchIndex>=0)openMedia(searchResults[searchIndex]);else if(input.value.trim().length>=2)runSearch(input.value.trim())}else if(event.key==='Escape')document.querySelector('#universe-search').classList.remove('open')},{capture:true});document.addEventListener('click',event=>{if(!event.target.closest('.search'))document.querySelector('#universe-search')?.classList.remove('open')});document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(!['ask','notifications'].includes(action))return;event.preventDefault();event.stopImmediatePropagation();if(action==='ask')openAssistant();else openNotifications()},{capture:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupCompanionUI);else setupCompanionUI();
